[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd backend && npm install"
]

[phases.build]
cmds = [
  "cd backend && npx prisma generate",
  "cd backend && npm run build"
]

[start]
cmd = "cd backend && npx prisma db push && node dist/index.js"
